parameters:
  toolchain: 'clang'
  mode: 'debug'

jobs:
  - job: 'Linux_${{ parameters.toolchain }}_${{ parameters.mode }}'

    pool:
      vmImage: ubuntu-latest

    steps:
    - template: setup.yml

    - ${{ if eq(parameters.toolchain, 'clang') }}:
      - script: |
          sudo apt-get install -y clang lld llvm
        displayName: 'Dependencies'

    - ${{ if eq(parameters.toolchain, 'gcc') }}:
      - script: |
          sudo apt-get install -y  gcc g++ lcov lld
        displayName: 'Dependencies'

    - script: |
        make install
      displayName: 'Install'
      failOnStderr: true

    - script: |
        echo "##vso[task.setvariable variable=config]mode=${{ parameters.mode }} toolchain=${{ parameters.toolchain }} coverage=1"
      displayName: 'Configure'

    - script: |
        make -C examples $(config) clean
        make -C examples $(config)
        make -C examples $(config) tests
      displayName: 'Examples (single-process)'
      failOnStderr: true

    - script: |
        make -j $(nproc) -C examples $(config) clean
        make -j $(nproc) -C examples $(config)
        make -j $(nproc) -C examples $(config) tests
      displayName: 'Examples (multi-process)'
      failOnStderr: true

    - ${{ if eq(parameters.mode, 'debug') }}:
      - script: |
          make -j $(nproc) -C examples $(config) coverage
        displayName: 'Coverage'
        failOnStderr: true

    - ${{ if eq(parameters.toolchain, 'clang') }}:
      - ${{ if eq(parameters.mode, 'release') }}:
        - template: package.yml
          parameters:
            contents: 'out/flymake-*.tar.bz2'
