parameters:
  contents: ''

steps:
- task: CopyFiles@2
  inputs:
    contents: ${{ parameters.contents }}
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
  displayName: 'Collect'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: flymake
  displayName: 'Publish'

- task: GitHubRelease@0
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    action: 'edit'
    tag: $(Build.SourceBranchName)
    tagSource: 'Git tag'
    gitHubConnection: trflynn89
    repositoryName: trflynn89/flymake
    assets: $(Build.ArtifactStagingDirectory)/*
    assetUploadMode: 'replace'
  displayName: Release
